### ISSUE TITLE
Image processing

### ISSUE THREAD

**Issue by dwHou** [flaport/torch_lfilter#1]
Hi, thank you for your beautiful coding , do you have any plan to extend this work to 2D-filter?

**Comment by flaport** [comment]
For the moment this is not on any plan. What kind of filter are you thinking of? Isn't an *lfilter* inherently 1D (look for example at scipy's *lfilter*)?

**Comment by dwHou** [comment]
> For the moment this is not on any plan. What kind of filter are you thinking of? Isn't an _lfilter_ inherently 1D (look for example at scipy's _lfilter_)?

Yes, and I found some other implements of manually-designed filters in [kornia](https://kornia.readthedocs.io/en/latest/filters.html). It is a differentiable computer vision library. Maybe It can be said to be similar to your work and motivation

**Comment by flaport** [comment]
I never really had computer vision in mind when designing this library. I just wanted a differentiable alternative to scipy's lfilter that was relatively performant for low pass filtering time series...

Closing this for now as I don't see myself adding many additions to the bare lfilter implementation.
